import Head from "next/head";
import { HomeTemplate } from "../containers";

export default function Home() {
  return (
    <>
      <Head>
        <title>Beatiful DND</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeTemplate />
    </>
  );
}
